import React from "react";
import Layout from "@/components/Layout";
import Head from "next/head";
import AnimatedText from "@/components/AnimatedText";
import TransitionEffect from "@/components/TransitionEffect";
import Link from "next/link";
import { GithubIcon } from "@/components/Icons";
import Image from "next/image";
import FeaturedProjectimg1 from "../../public/images/projects/fashion-studio-website.jpg";

const FeaturedProjects = ({ type, title, summary, img, link, github }) => {
  return (
    <article className="w-full flex items-center justify-between rounded-3xl border border-solid border-dark bg-light shadow-2xl">
      <Link
        href={link}
        target="_blank"
        className="w-1/2 cursor-pointer rounded-lg overflow-hidden"
      >
        <Image src={img} alt={title} className="w-full h-auto" />
      </Link>

      <div className="w-full flex flex-col items-start justify-between pl-6">
        <span className="text-primary font-medium text-xl">{type}</span>
        <Link href={link} target="_blank">
          <h2>{title}</h2>
        </Link>
        <p>{summary}</p>
        <div>
          <Link href={github} target="_blank">
            <GithubIcon />
          </Link>
          <Link href={link} target="_blank">
            Visit Project
          </Link>
        </div>
      </div>
    </article>
  );
};

const projects = () => {
  return (
    <>
      <Head>
        <title>Projects Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* <TransitionEffect /> */}
      <main className="w-full mb-16 flex flex-col items-center justify-center">
        <Layout className="pt-16">
          <AnimatedText
            text="Imagination triumphs knowledge!"
            className="text-center mb-16"
          />
          <div className="grid grid-cols-12 gap-24">
            <div className="col-span-12">
              <FeaturedProjects
                type="Featured"
                title="E-Commerce Website"
                summary="This is a E-Commerce Website made using ReactJS, Redux, Firebase, Stripe, and Styled Components."
                img={FeaturedProjectimg1}
                link="https://ecommerce-website-raj.netlify.app/"
                github=" /"
              />
            </div>
            <div className="col-span-6"> Projects 1</div>
            <div className="col-span-6">Featured 2</div>
            <div className="col-span-12">Featured Projects</div>
            <div className="col-span-6"> Projects 3</div>
            <div className="col-span-6">Featured 4</div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default projects;
